// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CategoryController from "./category_controller"
application.register("category", CategoryController)

import ChangeStyleInputController from "./change_style_input_controller"
application.register("change-style-input", ChangeStyleInputController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
